language: java

branches:
    except:
        - gh-pages

notifications:
    email:
        - sayhello@josomers.be

before_install:
    # download the latest android sdk and unzip
    - wget https://dl.google.com/android/android-sdk_r22-linux.tgz
    - tar -zxf android-sdk_r22-linux.tgz
    - export ANDROID_HOME=`pwd`/android-sdk-linux
    - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
    - android update sdk --filter 1,2,3,4,6 --no-ui --force
    # Create and start emulator
    - echo no | android create avd --force -n test -t android-16 --abi armeabi-v7a --sdcard 15M
    - emulator -avd test -no-skin -no-audio -no-window &

script: mvn install -Dandroid.device=test